# Generated by Django 3.2.4 on 2021-06-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='descripcionDenuncia',
            field=models.CharField(max_length=300, verbose_name='descripcionDenuncia'),
        ),
    ]
